type = "webpack"
route = ""
workers_dev = true
zone_id = "64032f9bb3e15226843c6c3cf40fc4ca"
name = ""
account_id = "126f4a0c75180e9493cb3716f5178574"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.prod]
name = "mss-boot-docs"
route = "docs.mss-boot-io.top/*"